#!/bin/sh
set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	dpkg-maintscript-helper mv_conffile /etc/php5/conf.d/yaf.ini \
		/etc/php5/mods-available/yaf.ini
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
