#!/bin/sh
set -e

dpkg-maintscript-helper mv_conffile /etc/php5/conf.d/yaf.ini \
	/etc/php5/mods-available/yaf.ini -- "$@"

case "$1" in
    configure)
		if [ -f /usr/sbin/php5enmod ] ; then
			php5enmod yaf
		else
			ln -s /etc/php5/mods-available/yaf.ini /etc/php5/conf.d/yaf.ini
		fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
