#!/bin/sh
set -e

dpkg-maintscript-helper mv_conffile /etc/php5/conf.d/yaf.ini \
	/etc/php5/mods-available/yaf.ini -- "$@"

case "$1" in
    install|upgrade)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
