#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
	locate php5dismod
	if [ $? -eq 0 ] ; then
		php5dismod yaf
	else
		find -name "*yaf.ini" /etc/php5/conf.d/ --delete
	fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
